import { saveAs } from 'file-saver'
import type { OutputFormat } from '@/types'

export function downloadReport(content: string, clientName: string, format: OutputFormat) {
  const date = new Date().toISOString().split('T')[0]
  const safeName = clientName.replace(/[^a-z0-9]/gi, '_') || 'Client'
  const filename = `${safeName}_SEO_Report_${date}`

  if (format === 'html') {
    const html = markdownToHtml(content, clientName)
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
    saveAs(blob, `${filename}.html`)
  } else {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    saveAs(blob, `${filename}.md`)
  }
}

function markdownToHtml(md: string, title: string): string {
  const esc = (s: string) => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
  const lines = md.split('\n')
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)} — SEO Report</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap');
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Space Grotesk',sans-serif;background:#f8fafc;color:#1e293b;line-height:1.7;padding:0}
    .wrapper{max-width:860px;margin:0 auto;padding:48px 32px}
    .cover{background:linear-gradient(135deg,#0A1628,#1A3C6E);color:#fff;padding:48px 32px;border-radius:16px;margin-bottom:40px}
    .cover h1{font-size:32px;font-weight:700;margin-bottom:8px}
    .cover p{opacity:.7;font-size:14px}
    h1{color:#1A3C6E;font-size:26px;font-weight:700;margin:36px 0 12px;padding-bottom:8px;border-bottom:3px solid #2E75B6}
    h2{color:#2563EB;font-size:18px;font-weight:600;margin:24px 0 10px}
    h3{color:#475569;font-size:15px;font-weight:600;margin:18px 0 8px}
    p{margin:8px 0;font-size:14px}
    li{margin:5px 0;font-size:14px;padding-left:4px}
    ul{padding-left:24px;margin:8px 0}
    hr{border:none;border-top:2px solid #e2e8f0;margin:32px 0}
    table{border-collapse:collapse;width:100%;margin:16px 0;font-size:13px;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)}
    th{background:#1A3C6E;color:#fff;padding:10px 16px;text-align:left;font-weight:600}
    td{border:1px solid #e2e8f0;padding:8px 16px}
    tr:nth-child(even) td{background:#f8fafc}
    code{background:#f1f5f9;padding:2px 6px;border-radius:4px;font-family:monospace;font-size:12px}
    .footer{text-align:center;color:#94a3b8;font-size:12px;margin-top:48px;padding-top:24px;border-top:1px solid #e2e8f0}
  </style>
</head>
<body>
<div class="wrapper">
<div class="cover">
  <h1>${esc(title)} — SEO Performance Report</h1>
  <p>Generated ${new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'})}</p>
</div>\n`

  let inList = false
  lines.forEach(line => {
    const l = line

    if (!l.startsWith('- ') && !l.startsWith('* ') && inList) {
      html += '</ul>\n'
      inList = false
    }

    if (l.startsWith('# '))        html += `<h1>${esc(l.slice(2))}</h1>\n`
    else if (l.startsWith('## '))  html += `<h2>${esc(l.slice(3))}</h2>\n`
    else if (l.startsWith('### ')) html += `<h3>${esc(l.slice(4))}</h3>\n`
    else if (l.startsWith('- ') || l.startsWith('* ')) {
      if (!inList) { html += '<ul>\n'; inList = true }
      html += `<li>${esc(l.slice(2))}</li>\n`
    }
    else if (l === '---') html += '<hr/>\n'
    else if (l.startsWith('|') && !l.match(/^\|[-\s|]+\|$/)) {
      const cells = l.split('|').filter(c => c.trim())
      html += `<tr>${cells.map(c => `<td>${esc(c.trim())}</td>`).join('')}</tr>\n`
    }
    else if (l.trim()) html += `<p>${esc(l)}</p>\n`
    else if (l === '') html += '\n'
  })

  html += `<div class="footer">Generated by SEO Report Generator · Powered by Claude AI</div>
</div></body></html>`
  return html
}
